### ISSUE TITLE
Crashing because of  runtime problem "Cannot find static method getFont"

### ISSUE THREAD

**Issue by izderadicka** [googlesamples/android-MediaBrowserService#6]
Problem was in the Application build.gradle.script, this depenency was older then other support libraries:
```
compile 'com.android.support:appcompat-v7:26.1.0'
```
upgrading it to 27.0.2 fixed the issue

**Comment by Sun3** [comment]
I had the same issue, thanks for posting the solution.

**Comment by ThePredators** [comment]
Still have the same issue ! 

`2018-05-22 20:10:32.014 19004-19004/com.example.android.mediasession E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.mediasession, PID: 19004
    java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.example.android.mediasession-1/base.apk)
        at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
        at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
        at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
        at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:67)
        at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:753)
        at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
        at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
        at android.support.v7.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:621)
        at android.support.v7.app.AppCompatDelegateImplV9.onTitleChanged(AppCompatDelegateImplV9.java:631)
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.example.android.mediasession.ui.MainActivity.onCreate(MainActivity.java:55)
        at android.app.Activity.performCreate(Activity.java:6955)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)`

**Comment by tcarlisle2012** [comment]
Thanks izderadicka! Still an issue as of September 2018.

**Comment by cartland** [comment]
Hello, I suggest looking at the "UAMP" sample: https://github.com/googlesamples/android-UniversalMusicPlayer.

The UAMP sample contains a MediaBrowserService implementation that works with more Android features.
https://android-developers.googleblog.com/2018/06/a-new-universal-music-player.html
https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af

If you still see this issue in the UAMP sample, please open an issue there. Thank you!

**Comment by mebjas** [comment]
> Problem was in the Application build.gradle.script, this depenency was older then other support libraries:
> 
> ```
> compile 'com.android.support:appcompat-v7:26.1.0'
> ```
> 
> upgrading it to 27.0.2 fixed the issue

The app crashes without this. It'd be a good idea to merge this in gradle script.
